---
abstract: 'Enables users to place advisory locks on tickets'
author:
  - 'Turner Hayes <thayes@bestpractical.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: GPL2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-TicketLocking
no_index:
  directory:
    - etc
    - html
    - po
    - var
    - inc
    - t
requires:
  perl: 5.8.3
version: 0.10
